const express=require("express");
const productController = require('../controllers/productController');
const verifyAdminToken=require('../middleware/verifyAdminToken');
const router=express.Router();
router.post('/add',verifyAdminToken,productController.addProduct);
router.get('/',productController.getProducts);
router.get('/:id',productController.getProduct);
router.put('/:productId',verifyAdminToken,productController.updateProduct);
router.delete('/:id',productController.deleteProduct);
module.exports=router;
