name: Deploy Ombrello Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t integrationninjas/ombrello-backend  .
      - name: Publish Image to docker hub
        run: docker push integrationninjas/ombrello-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull integrationninjas/ombrello-backend:latest
      - name: Delete old container
        run: docker rm -f ombrello-backend-app-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name ombrello-backend-app-container integrationninjas/ombrello-backend:latest
